#!/usr/bin/env node
/**
 * 生成 ECDICT 格式示例词库（~500 词，均匀覆盖 6 个级别）
 *
 * 用法:
 *   cd backend && node scripts/generateSample.js > ecdict_sample.csv
 */

// ===== 词库数据：按级别分类 =====
// 格式: [word, phonetic, definition, translation, pos, collins, oxford, tag, bnc, frq, exchange]
// tag 中第一个标签决定归属哪个单词书

const CET4 = [
  ["abandon","/əˈbændən/","v. to give up completely","v. 放弃；抛弃","v.",2,1,"cet4",2312,4.2,"0:abandons/1:abandoning/2:abandoned"],
  ["ability","/əˈbɪləti/","n. the capacity to do something","n. 能力；才能","n.",3,1,"cet4",1987,4.5,"0:abilities"],
  ["abroad","/əˈbrɔːd/","adv. in or to a foreign country","adv. 在国外；到国外","adv.",3,0,"cet4",2654,3.9,""],
  ["absent","/ˈæbsənt/","adj. not present in a place","adj. 缺席的；不在的","adj.",3,0,"cet4",3456,3.4,""],
  ["absolute","/ˈæbsəluːt/","adj. total and complete","adj. 绝对的；完全的","adj.",3,0,"cet4",3876,3.3,""],
  ["absorb","/əbˈzɔːrb/","v. to take in or soak up","v. 吸收；吸引","v.",3,0,"cet4",4321,3.0,"0:absorbs/1:absorbing/2:absorbed"],
  ["abstract","/ˈæbstrækt/","adj. existing in thought or as an idea","adj. 抽象的；n. 摘要","adj.",3,1,"cet4",2587,3.9,"0:abstracts"],
  ["abundant","/əˈbʌndənt/","adj. existing in large quantities","adj. 丰富的；充裕的","adj.",3,0,"cet4",6543,2.2,""],
  ["abuse","/əˈbjuːz/","v. to use something for the wrong purpose","v. 滥用；虐待；n. 滥用","v.",3,0,"cet4",2134,4.1,"0:abuses/1:abusing/2:abused"],
  ["academic","/ˌækəˈdemɪk/","adj. relating to education and scholarship","adj. 学术的；学院的","adj.",4,1,"cet4",1870,4.5,"0:academics"],
  ["accelerate","/əkˈseləreɪt/","v. to begin to move more quickly","v. 加速；促进","v.",3,0,"cet4",4723,3.1,"0:accelerates/1:accelerating/2:accelerated"],
  ["access","/ˈækses/","n. the means or opportunity to approach","n. 通道；进入权；v. 访问","n.",4,1,"cet4",1098,5.0,"0:accesses/1:accessing/2:accessed"],
  ["accommodate","/əˈkɑːmədeɪt/","v. to provide lodging or room for","v. 容纳；为……提供住宿","v.",3,0,"cet4",3156,3.6,"0:accommodates/1:accommodating/2:accommodated"],
  ["accompany","/əˈkʌmpəni/","v. to go somewhere with someone","v. 陪伴；伴随；为……伴奏","v.",3,0,"cet4",2890,3.8,"0:accompanies/1:accompanying/2:accompanied"],
  ["accomplish","/əˈkɑːmplɪʃ/","v. to achieve or complete successfully","v. 完成；实现","v.",3,0,"cet4",3782,3.4,"0:accomplishes/1:accomplishing/2:accomplished"],
  ["accurate","/ˈækjərət/","adj. correct in all details; exact","adj. 准确的；精确的","adj.",3,0,"cet4",2976,3.7,""],
  ["achieve","/əˈtʃiːv/","v. to successfully bring about or reach","v. 达到；取得；实现","v.",4,1,"cet4",1258,4.8,"0:achieves/1:achieving/2:achieved"],
  ["acknowledge","/əkˈnɑːlɪdʒ/","v. to accept or admit the existence of","v. 承认；确认；致谢","v.",3,0,"cet4",2987,3.7,"0:acknowledges/1:acknowledging/2:acknowledged"],
  ["acquire","/əˈkwaɪər/","v. to buy or obtain an asset or object","v. 获得；学到；收购","v.",4,0,"cet4",1987,4.4,"0:acquires/1:acquiring/2:acquired"],
  ["adapt","/əˈdæpt/","v. to make suitable for a new use","v. 适应；改编","v.",3,0,"cet4",3321,3.5,"0:adapts/1:adapting/2:adapted"],
  ["adequate","/ˈædɪkwət/","adj. satisfactory or acceptable in quality","adj. 足够的；适当的","adj.",3,0,"cet4",3876,3.3,""],
  ["adjust","/əˈdʒʌst/","v. to alter or move slightly","v. 调整；适应；校准","v.",3,0,"cet4",3121,3.5,"0:adjusts/1:adjusting/2:adjusted"],
  ["administration","/ədˌmɪnɪˈstreɪʃn/","n. the process of running a business","n. 管理；行政；行政部门","n.",4,0,"cet4",2134,4.1,"0:administrations"],
  ["admit","/ədˈmɪt/","v. to confess to be true","v. 承认；准许进入","v.",4,0,"cet4",1678,4.6,"0:admits/1:admitting/2:admitted"],
  ["adopt","/əˈdɑːpt/","v. to legally take another's child","v. 采用；收养；正式通过","v.",3,0,"cet4",2891,3.8,"0:adopts/1:adopting/2:adopted"],
  ["advance","/ədˈvæns/","n. a forward movement; v. to move forward","n. 前进；进步；v. 前进","n.",4,1,"cet4",1543,4.7,"0:advances/1:advancing/2:advanced"],
  ["advantage","/ədˈvæntɪdʒ/","n. a condition giving a greater chance","n. 优势；有利条件","n.",4,0,"cet4",1890,4.5,"0:advantages"],
  ["affair","/əˈfer/","n. an event or sequence of events","n. 事件；事务；私事","n.",3,0,"cet4",2789,3.8,"0:affairs"],
  ["affect","/əˈfekt/","v. to have an effect on; make a difference","v. 影响；感动；假装","v.",4,1,"cet4",1345,4.9,"0:affects/1:affecting/2:affected"],
  ["afford","/əˈfɔːrd/","v. to have enough money to pay for","v. 负担得起；提供","v.",3,0,"cet4",2345,4.0,"0:affords/1:affording/2:afforded"],
  ["agency","/ˈeɪdʒənsi/","n. a business providing a particular service","n. 代理机构；中介","n.",3,0,"cet4",3120,3.5,"0:agencies"],
  ["agenda","/əˈdʒendə/","n. a list of items to be discussed","n. 议程；议事日程","n.",3,0,"cet4",4321,3.0,"0:agendas"],
  ["aggressive","/əˈɡresɪv/","adj. ready to attack or confront","adj. 侵略的；好斗的；进取的","adj.",3,0,"cet4",3890,3.3,""],
  ["agreement","/əˈɡriːmənt/","n. a negotiated arrangement","n. 协议；同意；一致","n.",4,0,"cet4",1678,4.6,"0:agreements"],
  ["alarm","/əˈlɑːrm/","n. a warning of danger","n. 警报；闹钟；v. 使惊恐","n.",3,0,"cet4",3987,3.2,"0:alarms/1:alarming/2:alarmed"],
  ["alcohol","/ˈælkəhɔːl/","n. a drink containing ethanol","n. 酒精；含酒精饮料","n.",3,0,"cet4",3876,3.3,""],
  ["allowance","/əˈlaʊəns/","n. an amount of money given regularly","n. 津贴；零用钱；限额","n.",3,0,"cet4",5432,2.6,"0:allowances"],
  ["alongside","/əˈlɔːŋsaɪd/","prep. next to or at the side of","prep. 在……旁边；与……一起","prep.",3,0,"cet4",4890,2.9,""],
  ["alter","/ˈɔːltər/","v. to change or modify","v. 改变；修改","v.",3,0,"cet4",3987,3.2,"0:alters/1:altering/2:altered"],
  ["alternative","/ɔːlˈtɜːrnətɪv/","n. one of two or more possibilities","n. 替代方案；adj. 替代的","n.",4,0,"cet4",2678,3.8,"0:alternatives"],
  ["amaze","/əˈmeɪz/","v. to surprise someone greatly","v. 使惊讶；使惊奇","v.",3,0,"cet4",5120,2.8,"0:amazes/1:amazing/2:amazed"],
  ["ambition","/æmˈbɪʃn/","n. a strong desire to do or achieve","n. 雄心；野心；抱负","n.",3,0,"cet4",3456,3.4,"0:ambitions"],
  ["ambulance","/ˈæmbjələns/","n. a vehicle for taking sick people to hospital","n. 救护车","n.",2,0,"cet4",6789,2.1,"0:ambulances"],
  ["amount","/əˈmaʊnt/","n. a quantity of something","n. 数量；金额；v. 总计","n.",4,1,"cet4",1234,4.9,"0:amounts"],
  ["amuse","/əˈmjuːz/","v. to cause someone to find something funny","v. 娱乐；逗乐；使发笑","v.",3,0,"cet4",5432,2.6,"0:amuses/1:amusing/2:amused"],
  ["analyze","/ˈænəlaɪz/","v. to examine methodically","v. 分析；解析","v.",3,0,"cet4",2987,3.7,"0:analyzes/1:analyzing/2:analyzed"],
  ["ancestor","/ˈænsestər/","n. a person from whom one is descended","n. 祖先；祖宗","n.",3,0,"cet4",5432,2.6,"0:ancestors"],
  ["anchor","/ˈæŋkər/","n. a heavy device used to moor a ship","n. 锚；新闻主播；v. 固定","n.",3,0,"cet4",5678,2.5,"0:anchors/1:anchoring/2:anchored"],
  ["angle","/ˈæŋɡl/","n. the space between two intersecting lines","n. 角度；视角；v. 使成角度","n.",3,0,"cet4",3987,3.2,"0:angles"],
  ["anniversary","/ˌænɪˈvɜːrsəri/","n. the date of a past event","n. 周年纪念日","n.",3,0,"cet4",5432,2.6,"0:anniversaries"],
  ["announce","/əˈnaʊns/","v. to make a public declaration","v. 宣布；宣告；通知","v.",3,0,"cet4",2345,4.0,"0:announces/1:announcing/2:announced"],
  ["annoy","/əˈnɔɪ/","v. to make someone slightly angry","v. 使恼怒；打扰","v.",3,0,"cet4",4567,2.9,"0:annoys/1:annoying/2:annoyed"],
  ["annual","/ˈænjuəl/","adj. occurring once every year","adj. 年度的；每年的","adj.",4,0,"cet4",2678,3.8,""],
  ["anticipate","/ænˈtɪsɪpeɪt/","v. to regard as probable","v. 预期；期望；预先准备","v.",3,0,"cet4",3890,3.3,"0:anticipates/1:anticipating/2:anticipated"],
  ["anxiety","/æŋˈzaɪəti/","n. a feeling of worry or unease","n. 焦虑；忧虑；渴望","n.",3,0,"cet4",3987,3.2,"0:anxieties"],
  ["apart","/əˈpɑːrt/","adv. separated by a distance","adv. 分开地；相隔；adj. 分离的","adv.",3,0,"cet4",2789,3.8,""],
  ["apology","/əˈpɑːlədʒi/","n. a regretful acknowledgment of an offense","n. 道歉；歉意","n.",3,0,"cet4",4890,2.9,"0:apologies"],
  ["apparent","/əˈpærənt/","adj. clearly visible or understood; obvious","adj. 明显的；表面上的","adj.",3,0,"cet4",3456,3.4,""],
  ["appeal","/əˈpiːl/","v. to make a serious or urgent request","v. 呼吁；吸引；上诉；n. 吸引力","v.",3,0,"cet4",2987,3.7,"0:appeals/1:appealing/2:appealed"],
  ["appetite","/ˈæpɪtaɪt/","n. a natural desire to satisfy a bodily need","n. 胃口；食欲；欲望","n.",3,0,"cet4",4890,2.9,""],
  ["appliance","/əˈplaɪəns/","n. a device for a particular task","n. 电器；器具；设备","n.",3,0,"cet4",5432,2.6,"0:appliances"],
  ["application","/ˌæplɪˈkeɪʃn/","n. a formal request to an authority","n. 申请；应用；应用程序","n.",4,0,"cet4",1876,4.5,"0:applications"],
  ["apply","/əˈplaɪ/","v. to make a formal request","v. 申请；应用；适用","v.",4,1,"cet4",1456,4.7,"0:applies/1:applying/2:applied"],
  ["appoint","/əˈpɔɪnt/","v. to assign a job or role to someone","v. 任命；指定；约定","v.",3,0,"cet4",3987,3.2,"0:appoints/1:appointing/2:appointed"],
  ["appreciate","/əˈpriːʃieɪt/","v. to recognize the full worth of","v. 欣赏；感激；领会","v.",3,0,"cet4",2987,3.7,"0:appreciates/1:appreciating/2:appreciated"],
  ["approach","/əˈproʊtʃ/","v. to come near or nearer to","v. 接近；处理；n. 方法","v.",4,1,"cet4",1345,4.9,"0:approaches/1:approaching/2:approached"],
  ["appropriate","/əˈproʊpriət/","adj. suitable or proper","adj. 适当的；合适的","adj.",4,0,"cet4",2134,4.1,""],
  ["approve","/əˈpruːv/","v. to officially agree to or accept","v. 批准；赞成；认可","v.",3,0,"cet4",2678,3.8,"0:approves/1:approving/2:approved"],
  ["arise","/əˈraɪz/","v. to come into being; occur","v. 出现；产生；起床","v.",3,0,"cet4",3120,3.5,"0:arises/1:arising/2:arose/3:arisen"],
  ["arouse","/əˈraʊz/","v. to evoke or awaken a feeling","v. 唤醒；引起；激发","v.",3,0,"cet4",4890,2.9,"0:arouses/1:arousing/2:aroused"],
  ["arrange","/əˈreɪndʒ/","v. to put in a neat or required order","v. 安排；整理；布置","v.",3,0,"cet4",2987,3.7,"0:arranges/1:arranging/2:arranged"],
  ["arrest","/əˈrest/","v. to seize someone by legal authority","v. 逮捕；阻止；n. 逮捕","v.",3,0,"cet4",3456,3.4,"0:arrests/1:arresting/2:arrested"],
  ["artificial","/ˌɑːrtɪˈfɪʃl/","adj. made by human skill; not natural","adj. 人造的；人工的；虚假的","adj.",3,0,"cet4",4321,3.0,""],
  ["aspect","/ˈæspekt/","n. a particular part or feature","n. 方面；层面；外观","n.",4,0,"cet4",2134,4.1,"0:aspects"],
  ["assemble","/əˈsembl/","v. to gather together in one place","v. 集合；组装；聚集","v.",3,0,"cet4",3876,3.3,"0:assembles/1:assembling/2:assembled"],
  ["assess","/əˈses/","v. to evaluate or estimate the nature of","v. 评估；评定；估算","v.",4,0,"cet4",2678,3.8,"0:assesses/1:assessing/2:assessed"],
  ["asset","/ˈæset/","n. a useful or valuable thing or person","n. 资产；优点；有价值的人","n.",4,0,"cet4",2987,3.7,"0:assets"],
  ["assign","/əˈsaɪn/","v. to allocate a task or duty","v. 分配；指派；指定","v.",3,0,"cet4",3456,3.4,"0:assigns/1:assigning/2:assigned"],
  ["assist","/əˈsɪst/","v. to help someone by doing a share","v. 帮助；协助；援助","v.",3,0,"cet4",3120,3.5,"0:assists/1:assisting/2:assisted"],
  ["associate","/əˈsoʊʃieɪt/","v. to connect someone in one's mind","v. 联系；关联；n. 同事","v.",4,0,"cet4",2345,4.0,"0:associates/1:associating/2:associated"],
  ["assume","/əˈsuːm/","v. to suppose to be the case","v. 假设；承担；假装","v.",4,0,"cet4",1890,4.5,"0:assumes/1:assuming/2:assumed"],
  ["atmosphere","/ˈætməsfɪr/","n. the gases surrounding the earth","n. 大气层；气氛；氛围","n.",3,0,"cet4",3120,3.5,""],
  ["attach","/əˈtætʃ/","v. to fasten or join one thing to another","v. 附上；系上；附加","v.",3,0,"cet4",2678,3.8,"0:attaches/1:attaching/2:attached"],
];

const CET6 = [
  ["adolescent","/ˌædəˈlesnt/","n. a young person developing into an adult","n. 青少年；adj. 青春期的","n.",3,0,"cet6",5120,2.8,"0:adolescents"],
  ["adverse","/ˈædvɜːrs/","adj. preventing success or development","adj. 不利的；相反的；敌对的","adj.",3,0,"cet6",5678,2.5,""],
  ["advocate","/ˈædvəkeɪt/","v. to publicly recommend or support","v. 提倡；拥护；n. 倡导者","v.",3,0,"cet6",3987,3.2,"0:advocates/1:advocating/2:advocated"],
  ["aesthetic","/esˈθetɪk/","adj. concerned with beauty","adj. 美学的；审美的","adj.",3,0,"cet6",6789,2.1,""],
  ["aggregate","/ˈæɡrɪɡət/","n. a whole formed by combining elements","n. 合计；集合体；v. 聚集","n.",3,0,"cet6",7234,1.8,"0:aggregates/1:aggregating/2:aggregated"],
  ["allege","/əˈledʒ/","v. to claim or assert something","v. 指控；宣称；断言","v.",3,0,"cet6",5432,2.6,"0:alleges/1:alleging/2:alleged"],
  ["alleviate","/əˈliːvieɪt/","v. to make suffering less severe","v. 减轻；缓和；缓解","v.",3,0,"cet6",6780,2.1,"0:alleviates/1:alleviating/2:alleviated"],
  ["allocate","/ˈæləkeɪt/","v. to distribute resources for a purpose","v. 分配；拨出；指定","v.",3,0,"cet6",5432,2.6,"0:allocates/1:allocating/2:allocated"],
  ["ambiguous","/æmˈbɪɡjuəs/","adj. open to more than one interpretation","adj. 模棱两可的；含糊的","adj.",3,0,"cet6",5890,2.4,""],
  ["amend","/əˈmend/","v. to make minor changes to improve","v. 修改；修订；改善","v.",3,0,"cet6",5120,2.8,"0:amends/1:amending/2:amended"],
  ["analogy","/əˈnælədʒi/","n. a comparison between two things","n. 类比；比喻；类推","n.",3,0,"cet6",6345,2.3,"0:analogies"],
  ["anonymous","/əˈnɑːnɪməs/","adj. not identified by name","adj. 匿名的；不知名的","adj.",3,0,"cet6",5678,2.5,""],
  ["apparatus","/ˌæpəˈrætəs/","n. technical equipment or machinery","n. 设备；仪器；机构","n.",3,0,"cet6",6789,2.1,"0:apparatuses"],
  ["appraisal","/əˈpreɪzl/","n. an act of assessing something","n. 评价；评估；鉴定","n.",3,0,"cet6",7230,1.8,"0:appraisals"],
  ["articulate","/ɑːrˈtɪkjuleɪt/","v. to express an idea fluently","v. 明确表达；清楚说明","v.",3,0,"cet6",6123,2.4,"0:articulates/1:articulating/2:articulated"],
  ["ascertain","/ˌæsərˈteɪn/","v. to find something out for certain","v. 查明；确定；弄清","v.",3,0,"cet6",7230,1.8,"0:ascertains/1:ascertaining/2:ascertained"],
  ["assault","/əˈsɔːlt/","n. a physical attack","n. 攻击；袭击；v. 攻击","n.",3,0,"cet6",5432,2.6,"0:assaults/1:assaulting/2:assaulted"],
  ["assert","/əˈsɜːrt/","v. to state a fact or belief confidently","v. 断言；主张；坚持","v.",3,0,"cet6",4890,2.9,"0:asserts/1:asserting/2:asserted"],
  ["assimilate","/əˈsɪməleɪt/","v. to take in and fully understand","v. 吸收；同化；融入","v.",3,0,"cet6",7890,1.6,"0:assimilates/1:assimilating/2:assimilated"],
  ["authorize","/ˈɔːθəraɪz/","v. to give official permission for","v. 授权；批准；许可","v.",3,0,"cet6",5120,2.8,"0:authorizes/1:authorizing/2:authorized"],
  ["autonomous","/ɔːˈtɑːnəməs/","adj. having the freedom to govern itself","adj. 自治的；自主的","adj.",3,0,"cet6",6345,2.3,""],
  ["barrier","/ˈbæriər/","n. a fence or other obstacle","n. 障碍；屏障；隔阂","n.",3,0,"cet6",3121,3.5,"0:barriers"],
  ["benevolent","/bəˈnevələnt/","adj. well-meaning and kindly","adj. 仁慈的；慈善的","adj.",3,0,"cet6",8345,1.4,""],
  ["betray","/bɪˈtreɪ/","v. to expose to danger by giving info","v. 背叛；出卖；泄露","v.",3,0,"cet6",5890,2.4,"0:betrays/1:betraying/2:betrayed"],
  ["blueprint","/ˈbluːprɪnt/","n. a design plan or technical drawing","n. 蓝图；行动计划","n.",3,0,"cet6",7230,1.8,"0:blueprints"],
  ["bribe","/braɪb/","v. to dishonestly persuade someone","v. 贿赂；n. 贿赂物","v.",3,0,"cet6",6123,2.4,"0:bribes/1:bribing/2:bribed"],
  ["chronic","/ˈkrɑːnɪk/","adj. persisting for a long time","adj. 慢性的；长期的","adj.",3,0,"cet6",6123,2.4,""],
  ["circulate","/ˈsɜːrkjəleɪt/","v. to move through a closed system","v. 循环；流通；传播","v.",3,0,"cet6",4890,2.9,"0:circulates/1:circulating/2:circulated"],
  ["commence","/kəˈmens/","v. to begin or start","v. 开始；着手","v.",3,0,"cet6",5678,2.5,"0:commences/1:commencing/2:commenced"],
  ["commodity","/kəˈmɑːdəti/","n. a raw material or product","n. 商品；日用品","n.",4,0,"cet6",4567,2.9,"0:commodities"],
  ["compensate","/ˈkɑːmpenseɪt/","v. to give in recognition of loss","v. 补偿；赔偿；弥补","v.",3,0,"cet6",4890,2.9,"0:compensates/1:compensating/2:compensated"],
  ["complement","/ˈkɑːmplɪment/","v. to add to in a way that enhances","v. 补充；补足；n. 补充物","v.",3,0,"cet6",5432,2.6,"0:complements/1:complementing/2:complemented"],
  ["comprehensive","/ˌkɑːmprɪˈhensɪv/","adj. including all elements","adj. 全面的；综合的；详尽的","adj.",4,0,"cet6",3456,3.4,""],
  ["comprise","/kəmˈpraɪz/","v. to consist of; be made up of","v. 包含；包括；由……组成","v.",3,0,"cet6",4890,2.9,"0:comprises/1:comprising/2:comprised"],
  ["conceive","/kənˈsiːv/","v. to form a plan or become pregnant","v. 构思；设想；怀孕","v.",3,0,"cet6",5678,2.5,"0:conceives/1:conceiving/2:conceived"],
  ["conception","/kənˈsepʃn/","n. the action of conceiving","n. 概念；构想；怀孕","n.",3,0,"cet6",6123,2.4,"0:conceptions"],
  ["concise","/kənˈsaɪs/","adj. giving a lot of information clearly","adj. 简洁的；简明的","adj.",3,0,"cet6",6789,2.1,""],
  ["confer","/kənˈfɜːr/","v. to grant or bestow","v. 授予；商讨；协商","v.",3,0,"cet6",7230,1.8,"0:confers/1:conferring/2:conferred"],
  ["confine","/kənˈfaɪn/","v. to keep within limits","v. 限制；禁闭；n. 边界","v.",3,0,"cet6",4890,2.9,"0:confines/1:confining/2:confined"],
  ["conform","/kənˈfɔːrm/","v. to comply with rules or standards","v. 遵守；符合；顺应","v.",3,0,"cet6",5432,2.6,"0:conforms/1:conforming/2:conformed"],
  ["conscientious","/ˌkɑːnʃiˈenʃəs/","adj. wishing to do work thoroughly","adj. 认真的；尽责的","adj.",3,0,"cet6",7230,1.8,""],
  ["consolidate","/kənˈsɑːlɪdeɪt/","v. to make something stronger","v. 巩固；合并；统一","v.",3,0,"cet6",6123,2.4,"0:consolidates/1:consolidating/2:consolidated"],
  ["conspicuous","/kənˈspɪkjuəs/","adj. standing out clearly","adj. 显眼的；引人注目的","adj.",3,0,"cet6",7230,1.8,""],
  ["constitute","/ˈkɑːnstɪtuːt/","v. to be a part of a whole","v. 构成；组成；设立","v.",3,0,"cet6",4567,2.9,"0:constitutes/1:constituting/2:constituted"],
  ["constrain","/kənˈstreɪn/","v. to compel or force someone","v. 限制；约束；强迫","v.",3,0,"cet6",6123,2.4,"0:constrains/1:constraining/2:constrained"],
  ["contaminate","/kənˈtæmɪneɪt/","v. to make impure by exposure","v. 污染；弄脏；玷污","v.",3,0,"cet6",6789,2.1,"0:contaminates/1:contaminating/2:contaminated"],
  ["contemplate","/ˈkɑːntəmpleɪt/","v. to look thoughtfully","v. 沉思；考虑；注视","v.",3,0,"cet6",6123,2.4,"0:contemplates/1:contemplating/2:contemplated"],
  ["contempt","/kənˈtempt/","n. the feeling that a person is worthless","n. 蔑视；轻视","n.",3,0,"cet6",6789,2.1,""],
  ["contend","/kənˈtend/","v. to struggle to surmount","v. 竞争；争论；主张","v.",3,0,"cet6",6123,2.4,"0:contends/1:contending/2:contended"],
  ["contradict","/ˌkɑːntrəˈdɪkt/","v. to assert the opposite","v. 反驳；与……矛盾","v.",3,0,"cet6",5678,2.5,"0:contradicts/1:contradicting/2:contradicted"],
  ["controversy","/ˈkɑːntrəvɜːrsi/","n. prolonged public disagreement","n. 争议；争论；辩论","n.",3,0,"cet6",4890,2.9,"0:controversies"],
  ["convene","/kənˈviːn/","v. to come together for a meeting","v. 召集；召开；集会","v.",3,0,"cet6",6780,2.1,"0:convenes/1:convening/2:convened"],
  ["converge","/kənˈvɜːrdʒ/","v. to come together from different directions","v. 聚集；汇合；趋同","v.",3,0,"cet6",6789,2.1,"0:converges/1:converging/2:converged"],
  ["convict","/kənˈvɪkt/","v. to declare someone guilty","v. 定罪；宣判有罪；n. 罪犯","v.",3,0,"cet6",5678,2.5,"0:convicts/1:convicting/2:convicted"],
  ["coordinate","/koʊˈɔːrdɪneɪt/","v. to bring different elements together","v. 协调；配合；n. 坐标","v.",3,0,"cet6",4567,2.9,"0:coordinates/1:coordinating/2:coordinated"],
  ["correlate","/ˈkɔːrəleɪt/","v. to have a mutual relationship","v. 关联；相关；使相互关联","v.",3,0,"cet6",5678,2.5,"0:correlates/1:correlating/2:correlated"],
  ["corrode","/kəˈroʊd/","v. to destroy or damage slowly","v. 腐蚀；侵蚀","v.",3,0,"cet6",7230,1.8,"0:corrodes/1:corroding/2:corroded"],
  ["counsel","/ˈkaʊnsl/","n. advice given formally","n. 忠告；建议；法律顾问","n.",3,0,"cet6",6123,2.4,""],
  ["counterpart","/ˈkaʊntərpɑːrt/","n. a person or thing corresponding to another","n. 对应的人或物；副本","n.",3,0,"cet6",5678,2.5,"0:counterparts"],
  ["crucial","/ˈkruːʃl/","adj. decisive or critical","adj. 关键的；决定性的","adj.",4,0,"cet6",3456,3.4,""],
  ["cumulative","/ˈkjuːmjəleɪtɪv/","adj. increasing by successive additions","adj. 累积的；渐增的","adj.",3,0,"cet6",6789,2.1,""],
  ["dedicate","/ˈdedɪkeɪt/","v. to devote to a particular subject","v. 奉献；致力于；题献","v.",3,0,"cet6",4890,2.9,"0:dedicates/1:dedicating/2:dedicated"],
  ["deem","/diːm/","v. to regard or consider","v. 认为；视为；相信","v.",3,0,"cet6",5432,2.6,"0:deems/1:deeming/2:deemed"],
  ["deficiency","/dɪˈfɪʃnsi/","n. a lack or shortage","n. 缺陷；不足；缺乏","n.",3,0,"cet6",5678,2.5,"0:deficiencies"],
  ["deficit","/ˈdefɪsɪt/","n. the amount by which something is too small","n. 赤字；亏损；不足","n.",3,0,"cet6",5234,2.7,"0:deficits"],
  ["deliberate","/dɪˈlɪbərət/","adj. done consciously and intentionally","adj. 故意的；深思熟虑的","adj.",3,0,"cet6",5120,2.8,""],
  ["denote","/dɪˈnoʊt/","v. to be a sign of; indicate","v. 表示；指示；意味着","v.",3,0,"cet6",5678,2.5,"0:denotes/1:denoting/2:denoted"],
  ["depict","/dɪˈpɪkt/","v. to show or represent by a drawing","v. 描绘；描述；刻画","v.",3,0,"cet6",4890,2.9,"0:depicts/1:depicting/2:depicted"],
  ["deprive","/dɪˈpraɪv/","v. to prevent from having or using","v. 剥夺；使丧失","v.",3,0,"cet6",5120,2.8,"0:deprives/1:depriving/2:deprived"],
  ["designate","/ˈdezɪɡneɪt/","v. to officially assign a status","v. 指定；标明；任命","v.",3,0,"cet6",5432,2.6,"0:designates/1:designating/2:designated"],
  ["deteriorate","/dɪˈtɪriəreɪt/","v. to become progressively worse","v. 恶化；退化；变质","v.",3,0,"cet6",6123,2.4,"0:deteriorates/1:deteriorating/2:deteriorated"],
  ["deviate","/ˈdiːvieɪt/","v. to depart from an established course","v. 偏离；背离；越轨","v.",3,0,"cet6",6789,2.1,"0:deviates/1:deviating/2:deviated"],
  ["diagnose","/ˌdaɪəɡˈnoʊs/","v. to identify the nature of an illness","v. 诊断；判断","v.",3,0,"cet6",5432,2.6,"0:diagnoses/1:diagnosing/2:diagnosed"],
  ["differentiate","/ˌdɪfəˈrenʃieɪt/","v. to recognize what makes different","v. 区分；区别；使不同","v.",3,0,"cet6",4987,2.8,"0:differentiates/1:differentiating/2:differentiated"],
  ["diffuse","/dɪˈfjuːz/","v. to spread over a wide area","v. 扩散；传播；adj. 弥散的","v.",3,0,"cet6",6123,2.4,"0:diffuses/1:diffusing/2:diffused"],
  ["dilemma","/dɪˈlemə/","n. a situation requiring a difficult choice","n. 困境；进退两难","n.",3,0,"cet6",5678,2.5,"0:dilemmas"],
  ["dilute","/daɪˈluːt/","v. to make thinner or weaker","v. 稀释；冲淡；削弱","v.",3,0,"cet6",6789,2.1,"0:dilutes/1:diluting/2:diluted"],
  ["diminish","/dɪˈmɪnɪʃ/","v. to make or become less","v. 减少；缩小；减弱","v.",3,0,"cet6",4890,2.9,"0:diminishes/1:diminishing/2:diminished"],
];

const KAOYAN = [
  ["abolish","/əˈbɑːlɪʃ/","v. to formally put an end to","v. 废除；取消；废止","v.",3,0,"ky",5432,2.6,"0:abolishes/1:abolishing/2:abolished"],
  ["acquaint","/əˈkweɪnt/","v. to make someone aware of","v. 使熟悉；使了解","v.",3,0,"ky",7230,1.8,"0:acquaints/1:acquainting/2:acquainted"],
  ["adhere","/ədˈhɪr/","v. to stick firmly to","v. 遵守；粘附；坚持","v.",3,0,"ky",5678,2.5,"0:adheres/1:adhering/2:adhered"],
  ["adjacent","/əˈdʒeɪsnt/","adj. next to or adjoining","adj. 邻近的；毗邻的","adj.",3,0,"ky",6123,2.4,""],
  ["affiliate","/əˈfɪlieɪt/","v. to officially attach or connect","v. 使隶属；加入；n. 附属机构","v.",3,0,"ky",6789,2.1,"0:affiliates/1:affiliating/2:affiliated"],
  ["aggravate","/ˈæɡrəveɪt/","v. to make worse or more serious","v. 加重；恶化；激怒","v.",3,0,"ky",7230,1.8,"0:aggravates/1:aggravating/2:aggravated"],
  ["agitate","/ˈædʒɪteɪt/","v. to make someone troubled or nervous","v. 鼓动；煽动；使焦虑","v.",3,0,"ky",7890,1.6,"0:agitates/1:agitating/2:agitated"],
  ["alienate","/ˈeɪliəneɪt/","v. to cause to feel isolated","v. 使疏远；离间","v.",3,0,"ky",7230,1.8,"0:alienates/1:alienating/2:alienated"],
  ["allege","/əˈledʒ/","v. to claim without proof","v. 指控；宣称；断言","v.",3,0,"ky",5432,2.6,"0:alleges/1:alleging/2:alleged"],
  ["alliance","/əˈlaɪəns/","n. a union formed for mutual benefit","n. 联盟；联合；同盟","n.",3,0,"ky",4567,2.9,"0:alliances"],
  ["allot","/əˈlɑːt/","v. to give or apportion","v. 分配；拨出；指定","v.",3,0,"ky",7230,1.8,"0:allots/1:allotting/2:allotted"],
  ["alternate","/ˈɔːltərneɪt/","v. to occur in turn repeatedly","v. 交替；轮流；adj. 交替的","v.",3,0,"ky",5890,2.4,"0:alternates/1:alternating/2:alternated"],
  ["amplify","/ˈæmplɪfaɪ/","v. to increase the volume or strength","v. 放大；增强；详述","v.",3,0,"ky",6789,2.1,"0:amplifies/1:amplifying/2:amplified"],
  ["analogy","/əˈnælədʒi/","n. a comparison to show similarity","n. 类比；比喻；类推","n.",3,0,"ky",6345,2.3,"0:analogies"],
  ["anguish","/ˈæŋɡwɪʃ/","n. severe mental or physical pain","n. 痛苦；苦恼；v. 使痛苦","n.",3,0,"ky",7890,1.6,""],
  ["anonymous","/əˈnɑːnɪməs/","adj. having no known name","adj. 匿名的；无名的","adj.",3,0,"ky",5678,2.5,""],
  ["appal","/əˈpɔːl/","v. to greatly dismay or horrify","v. 使惊骇；使震惊","v.",3,0,"ky",8345,1.4,"0:appals/1:appalling/2:appalled"],
  ["appendix","/əˈpendɪks/","n. a section at the end of a book","n. 附录；阑尾","n.",3,0,"ky",6789,2.1,"0:appendices"],
  ["applaud","/əˈplɔːd/","v. to show approval by clapping","v. 鼓掌；称赞；赞许","v.",3,0,"ky",6123,2.4,"0:applauds/1:applauding/2:applauded"],
  ["apt","/æpt/","adj. appropriate or suitable","adj. 恰当的；有……倾向的","adj.",3,0,"ky",6789,2.1,""],
  ["arrogant","/ˈærəɡənt/","adj. having an exaggerated sense of ability","adj. 傲慢的；自大的","adj.",3,0,"ky",6123,2.4,""],
  ["artery","/ˈɑːrtəri/","n. a major blood vessel","n. 动脉；干线；要道","n.",3,0,"ky",7230,1.8,"0:arteries"],
  ["articulate","/ɑːrˈtɪkjuleɪt/","v. to express clearly","v. 明确表达；adj. 善于表达的","v.",3,0,"ky",6123,2.4,"0:articulates/1:articulating/2:articulated"],
  ["ascend","/əˈsend/","v. to go up or climb","v. 上升；攀登；登高","v.",3,0,"ky",5890,2.4,"0:ascends/1:ascending/2:ascended"],
  ["ascribe","/əˈskraɪb/","v. to attribute something to","v. 归因于；归咎于","v.",3,0,"ky",6789,2.1,"0:ascribes/1:ascribing/2:ascribed"],
  ["aspire","/əˈspaɪər/","v. to direct one's hopes toward","v. 渴望；有志于；追求","v.",3,0,"ky",7230,1.8,"0:aspires/1:aspiring/2:aspired"],
  ["assassinate","/əˈsæsɪneɪt/","v. to murder an important person","v. 暗杀；行刺","v.",3,0,"ky",8345,1.4,"0:assassinates/1:assassinating/2:assassinated"],
  ["assert","/əˈsɜːrt/","v. to state a fact confidently","v. 断言；主张；维护","v.",3,0,"ky",4890,2.9,"0:asserts/1:asserting/2:asserted"],
  ["assimilate","/əˈsɪməleɪt/","v. to absorb and integrate","v. 吸收；同化；融入","v.",3,0,"ky",7890,1.6,"0:assimilates/1:assimilating/2:assimilated"],
  ["attain","/əˈteɪn/","v. to succeed in achieving","v. 达到；获得；实现","v.",3,0,"ky",4567,2.9,"0:attains/1:attaining/2:attained"],
  ["auction","/ˈɔːkʃn/","n. a public sale of goods","n. 拍卖；v. 拍卖","n.",3,0,"ky",6123,2.4,"0:auctions/1:auctioning/2:auctioned"],
  ["audit","/ˈɔːdɪt/","n. an official inspection of accounts","n. 审计；审查；v. 审计","n.",3,0,"ky",6789,2.1,"0:audits/1:auditing/2:audited"],
  ["augment","/ɔːɡˈment/","v. to make something greater","v. 增加；增大；增强","v.",3,0,"ky",7230,1.8,"0:augments/1:augmenting/2:augmented"],
  ["autonomy","/ɔːˈtɑːnəmi/","n. the right of self-government","n. 自治；自主权","n.",3,0,"ky",5678,2.5,""],
  ["avail","/əˈveɪl/","v. to help or benefit","v. 有益于；有助于；n. 效用","v.",3,0,"ky",8345,1.4,"0:avails/1:availing/2:availed"],
  ["avert","/əˈvɜːrt/","v. to turn away or prevent","v. 避免；防止；转移","v.",3,0,"ky",7230,1.8,"0:averts/1:averting/2:averted"],
  ["awe","/ɔː/","n. a feeling of reverential respect","n. 敬畏；惊叹；v. 使敬畏","n.",3,0,"ky",8345,1.4,""],
  ["baffle","/ˈbæfl/","v. to totally bewilder or perplex","v. 使困惑；难住；阻碍","v.",3,0,"ky",6123,2.4,"0:baffles/1:baffling/2:baffled"],
  ["bald","/bɔːld/","adj. having no hair on the head","adj. 秃头的；光秃的；直白的","adj.",3,0,"ky",6123,2.4,""],
  ["bankrupt","/ˈbæŋkrʌpt/","adj. declared unable to pay debts","adj. 破产的；v. 使破产","adj.",3,0,"ky",5432,2.6,""],
  ["barren","/ˈbærən/","adj. unable to produce vegetation","adj. 贫瘠的；不育的；无效果的","adj.",3,0,"ky",6789,2.1,""],
  ["beforehand","/bɪˈfɔːrhænd/","adv. in advance; earlier","adv. 事先；预先","adv.",3,0,"ky",6123,2.4,""],
  ["besiege","/bɪˈsiːdʒ/","v. to surround with armed forces","v. 包围；围困；使烦恼","v.",3,0,"ky",7890,1.6,"0:besieges/1:besieging/2:besieged"],
  ["bewilder","/bɪˈwɪldər/","v. to cause to become perplexed","v. 使迷惑；使糊涂","v.",3,0,"ky",6789,2.1,"0:bewilders/1:bewildering/2:bewildered"],
  ["bias","/ˈbaɪəs/","n. inclination or prejudice","n. 偏见；偏爱；v. 使有偏见","n.",3,0,"ky",5678,2.5,"0:biases/1:biasing/2:biased"],
  ["bizarre","/bɪˈzɑːr/","adj. very strange or unusual","adj. 奇异的；古怪的","adj.",3,0,"ky",6123,2.4,""],
  ["blaze","/bleɪz/","n. a very large or fiercely burning fire","n. 火焰；光辉；v. 燃烧","n.",3,0,"ky",6789,2.1,"0:blazes/1:blazing/2:blazed"],
  ["bleak","/bliːk/","adj. cold and miserable","adj. 阴冷的；荒凉的；黯淡的","adj.",3,0,"ky",6123,2.4,""],
  ["blunder","/ˈblʌndər/","n. a stupid or careless mistake","n. 错误；大错；v. 犯大错","n.",3,0,"ky",6789,2.1,"0:blunders/1:blundering/2:blundered"],
  ["blunt","/blʌnt/","adj. having a worn-down edge","adj. 钝的；直率的；v. 使变钝","adj.",3,0,"ky",6123,2.4,""],
  ["boycott","/ˈbɔɪkɑːt/","v. to refuse to buy or participate","v. 抵制；排斥；n. 抵制","v.",3,0,"ky",6123,2.4,"0:boycotts/1:boycotting/2:boycotted"],
  ["breach","/briːtʃ/","n. an act of breaking a law or agreement","n. 违反；破坏；缺口；v. 违反","n.",3,0,"ky",5678,2.5,"0:breaches/1:breaching/2:breached"],
  ["brisk","/brɪsk/","adj. active, fast, and energetic","adj. 轻快的；活泼的；兴隆的","adj.",3,0,"ky",6789,2.1,""],
  ["bruise","/bruːz/","n. an injury appearing as discoloration","n. 瘀伤；伤痕；v. 使受伤","n.",3,0,"ky",7230,1.8,"0:bruises/1:bruising/2:bruised"],
  ["brutal","/ˈbruːtl/","adj. savagely violent","adj. 野蛮的；残忍的；无情的","adj.",3,0,"ky",5678,2.5,""],
  ["bully","/ˈbʊli/","n. a person who habitually intimidates","n. 欺凌者；v. 欺负；恐吓","n.",3,0,"ky",7230,1.8,"0:bullies/1:bullying/2:bullied"],
  ["bureaucracy","/bjʊˈrɑːkrəsi/","n. a system of government with many rules","n. 官僚机构；官僚主义","n.",3,0,"ky",7890,1.6,"0:bureaucracies"],
  ["calcium","/ˈkælsiəm/","n. a chemical element essential for living","n. 钙","n.",2,0,"ky",6345,2.3,""],
  ["catastrophe","/kəˈtæstrəfi/","n. an event causing great damage","n. 灾难；大祸；彻底失败","n.",3,0,"ky",6123,2.4,"0:catastrophes"],
  ["cater","/ˈkeɪtər/","v. to provide what is wanted or needed","v. 满足需求；提供饮食；迎合","v.",3,0,"ky",5678,2.5,"0:caters/1:catering/2:catered"],
  ["census","/ˈsensəs/","n. an official count of a population","n. 人口普查；统计","n.",3,0,"ky",6123,2.4,"0:censuses"],
  ["chronic","/ˈkrɑːnɪk/","adj. persisting for a long time","adj. 慢性的；长期的；习惯性的","adj.",3,0,"ky",6123,2.4,""],
  ["circulate","/ˈsɜːrkjəleɪt/","v. to move continuously through","v. 循环；流通；传播","v.",3,0,"ky",4890,2.9,"0:circulates/1:circulating/2:circulated"],
  ["clarity","/ˈklærəti/","n. the quality of being clear","n. 清晰；清楚；明晰","n.",3,0,"ky",5432,2.6,""],
  ["clash","/klæʃ/","v. to meet and come into conflict","v. 冲突；碰撞；不协调；n. 冲突","v.",3,0,"ky",5678,2.5,"0:clashes/1:clashing/2:clashed"],
  ["clasp","/klæsp/","v. to grasp something tightly","v. 紧握；扣紧；n. 扣子","v.",3,0,"ky",7230,1.8,"0:clasps/1:clasping/2:clasped"],
  ["clumsy","/ˈklʌmzi/","adj. awkward in movement or handling","adj. 笨拙的；不灵巧的","adj.",3,0,"ky",6123,2.4,""],
  ["coalition","/ˌkoʊəˈlɪʃn/","n. an alliance for combined action","n. 联盟；联合；同盟","n.",3,0,"ky",5432,2.6,"0:coalitions"],
  ["cognitive","/ˈkɑːɡnətɪv/","adj. relating to mental processes","adj. 认知的；认识的","adj.",3,0,"ky",5678,2.5,""],
  ["coherent","/koʊˈhɪrənt/","adj. logical and consistent","adj. 连贯的；一致的；清晰的","adj.",3,0,"ky",5432,2.6,""],
  ["coincide","/ˌkoʊɪnˈsaɪd/","v. to occur at the same time","v. 同时发生；巧合；一致","v.",3,0,"ky",5678,2.5,"0:coincides/1:coinciding/2:coincided"],
  ["collaborate","/kəˈlæbəreɪt/","v. to work jointly on an activity","v. 合作；协作；勾结","v.",3,0,"ky",5432,2.6,"0:collaborates/1:collaborating/2:collaborated"],
  ["collide","/kəˈlaɪd/","v. to crash violently into","v. 碰撞；冲突；抵触","v.",3,0,"ky",5678,2.5,"0:collides/1:colliding/2:collided"],
  ["commemorate","/kəˈmeməreɪt/","v. to honor the memory of","v. 纪念；庆祝","v.",3,0,"ky",6123,2.4,"0:commemorates/1:commemorating/2:commemorated"],
  ["commend","/kəˈmend/","v. to praise formally or officially","v. 表扬；称赞；推荐","v.",3,0,"ky",6789,2.1,"0:commends/1:commending/2:commended"],
  ["commonplace","/ˈkɑːmənpleɪs/","adj. not unusual; ordinary","adj. 平凡的；普通的；n. 寻常事","adj.",3,0,"ky",5678,2.5,""],
  ["commute","/kəˈmjuːt/","v. to travel regularly between home and work","v. 通勤；减刑；交换","v.",3,0,"ky",6123,2.4,"0:commutes/1:commuting/2:commuted"],
  ["compact","/ˈkɑːmpækt/","adj. closely and neatly packed","adj. 紧凑的；小巧的；v. 压缩","adj.",3,0,"ky",5432,2.6,""],
  ["compatible","/kəmˈpætəbl/","adj. able to exist together without conflict","adj. 兼容的；合得来的","adj.",3,0,"ky",4890,2.9,""],
  ["compile","/kəmˈpaɪl/","v. to produce by assembling information","v. 编译；汇编；编纂","v.",3,0,"ky",5432,2.6,"0:compiles/1:compiling/2:compiled"],
  ["comply","/kəmˈplaɪ/","v. to act in accordance with a wish","v. 遵守；遵从；服从","v.",3,0,"ky",4890,2.9,"0:complies/1:complying/2:complied"],
];

const TOEFL = [
  ["abolish","/əˈbɑːlɪʃ/","v. to formally put an end to","v. 废除；取消；废止","v.",3,0,"toefl",5432,2.6,"0:abolishes/1:abolishing/2:abolished"],
  ["abrupt","/əˈbrʌpt/","adj. sudden and unexpected","adj. 突然的；唐突的；陡峭的","adj.",3,0,"toefl",6123,2.4,""],
  ["absorb","/əbˈzɔːrb/","v. to take in or soak up","v. 吸收；吸引；同化","v.",3,0,"toefl",4321,3.0,"0:absorbs/1:absorbing/2:absorbed"],
  ["abstain","/əbˈsteɪn/","v. to restrain oneself from doing","v. 戒绝；弃权；避免","v.",3,0,"toefl",7230,1.8,"0:abstains/1:abstaining/2:abstained"],
  ["abundance","/əˈbʌndəns/","n. a very large quantity of something","n. 丰富；充裕；大量","n.",3,0,"toefl",5432,2.6,""],
  ["accelerate","/əkˈseləreɪt/","v. to increase in speed","v. 加速；促进","v.",3,0,"toefl",4723,3.1,"0:accelerates/1:accelerating/2:accelerated"],
  ["acclaim","/əˈkleɪm/","v. to praise enthusiastically","v. 称赞；赞扬；n. 喝彩","v.",3,0,"toefl",6789,2.1,"0:acclaims/1:acclaiming/2:acclaimed"],
  ["accommodate","/əˈkɑːmədeɪt/","v. to provide lodging or adjust to","v. 容纳；为……提供住宿；适应","v.",3,0,"toefl",3156,3.6,"0:accommodates/1:accommodating/2:accommodated"],
  ["accumulate","/əˈkjuːmjəleɪt/","v. to gather or pile up","v. 积累；积聚；堆积","v.",3,0,"toefl",4098,3.2,"0:accumulates/1:accumulating/2:accumulated"],
  ["acquaint","/əˈkweɪnt/","v. to make familiar with","v. 使熟悉；使了解；告知","v.",3,0,"toefl",7230,1.8,"0:acquaints/1:acquainting/2:acquainted"],
  ["adept","/əˈdept/","adj. very skilled or proficient","adj. 熟练的；擅长的；n. 能手","adj.",3,0,"toefl",7230,1.8,""],
  ["adhere","/ədˈhɪr/","v. to stick firmly to","v. 遵守；粘附；坚持","v.",3,0,"toefl",5678,2.5,"0:adheres/1:adhering/2:adhered"],
  ["adjacent","/əˈdʒeɪsnt/","adj. next to or adjoining something","adj. 邻近的；毗邻的","adj.",3,0,"toefl",6123,2.4,""],
  ["administer","/ədˈmɪnɪstər/","v. to manage or be responsible for","v. 管理；执行；给予","v.",3,0,"toefl",4890,2.9,"0:administers/1:administering/2:administered"],
  ["adolescent","/ˌædəˈlesnt/","n. a young person developing into an adult","n. 青少年；adj. 青春期的","n.",3,0,"toefl",5120,2.8,"0:adolescents"],
  ["advent","/ˈædvent/","n. the arrival of a notable thing","n. 到来；出现；降临","n.",3,0,"toefl",6123,2.4,""],
  ["adverse","/ˈædvɜːrs/","adj. harmful or unfavorable","adj. 不利的；相反的；敌对的","adj.",3,0,"toefl",5678,2.5,""],
  ["aesthetic","/esˈθetɪk/","adj. concerned with beauty","adj. 美学的；审美的；美观的","adj.",3,0,"toefl",6789,2.1,""],
  ["affiliate","/əˈfɪlieɪt/","v. to officially attach to an organization","v. 使隶属；加入；n. 附属机构","v.",3,0,"toefl",6789,2.1,"0:affiliates/1:affiliating/2:affiliated"],
  ["aggravate","/ˈæɡrəveɪt/","v. to make a problem worse","v. 加重；恶化；激怒","v.",3,0,"toefl",7230,1.8,"0:aggravates/1:aggravating/2:aggravated"],
  ["aggregate","/ˈæɡrɪɡət/","n. a whole formed by combination","n. 合计；集合体；v. 聚集","n.",3,0,"toefl",7234,1.8,"0:aggregates/1:aggregating/2:aggregated"],
  ["allege","/əˈledʒ/","v. to claim or assert without proof","v. 指控；宣称；断言","v.",3,0,"toefl",5432,2.6,"0:alleges/1:alleging/2:alleged"],
  ["alleviate","/əˈliːvieɪt/","v. to make suffering less severe","v. 减轻；缓和；缓解","v.",3,0,"toefl",6780,2.1,"0:alleviates/1:alleviating/2:alleviated"],
  ["allocate","/ˈæləkeɪt/","v. to distribute for a particular purpose","v. 分配；拨出；指定","v.",3,0,"toefl",5432,2.6,"0:allocates/1:allocating/2:allocated"],
  ["allure","/əˈlʊr/","v. to powerfully attract or charm","v. 诱惑；吸引；n. 魅力","v.",3,0,"toefl",7890,1.6,"0:allures/1:alluring/2:allured"],
  ["alteration","/ˌɔːltəˈreɪʃn/","n. the action of changing something","n. 改变；修改；变更","n.",3,0,"toefl",5678,2.5,"0:alterations"],
  ["ambiguous","/æmˈbɪɡjuəs/","adj. open to more than one interpretation","adj. 模棱两可的；含糊的","adj.",3,0,"toefl",5890,2.4,""],
  ["amend","/əˈmend/","v. to make minor changes to improve","v. 修改；修订；改善","v.",3,0,"toefl",5120,2.8,"0:amends/1:amending/2:amended"],
  ["analogy","/əˈnælədʒi/","n. a comparison between two things","n. 类比；比喻；类推","n.",3,0,"toefl",6345,2.3,"0:analogies"],
  ["anchor","/ˈæŋkər/","v. to secure firmly in position","v. 使固定；主持；n. 锚","v.",3,0,"toefl",5678,2.5,"0:anchors/1:anchoring/2:anchored"],
  ["anguish","/ˈæŋɡwɪʃ/","n. severe mental or physical pain","n. 痛苦；苦恼；v. 使痛苦","n.",3,0,"toefl",7890,1.6,""],
  ["animate","/ˈænɪmeɪt/","v. to bring to life or give motion","v. 使有生命；激励；制作动画","v.",3,0,"toefl",6789,2.1,"0:animates/1:animating/2:animated"],
  ["annex","/əˈneks/","v. to add as an extra part","v. 附加；吞并；n. 附属建筑","v.",3,0,"toefl",6789,2.1,"0:annexes/1:annexing/2:annexed"],
  ["anomaly","/əˈnɑːməli/","n. something that deviates from the norm","n. 异常；反常；不规则","n.",3,0,"toefl",7230,1.8,"0:anomalies"],
  ["anonymous","/əˈnɑːnɪməs/","adj. of unknown name or origin","adj. 匿名的；无名的","adj.",3,0,"toefl",5678,2.5,""],
  ["apparatus","/ˌæpəˈrætəs/","n. equipment needed for a particular task","n. 设备；仪器；机构","n.",3,0,"toefl",6789,2.1,"0:apparatuses"],
  ["appraisal","/əˈpreɪzl/","n. an assessment of worth or quality","n. 评价；评估；鉴定","n.",3,0,"toefl",7230,1.8,"0:appraisals"],
  ["appreciable","/əˈpriːʃəbl/","adj. large enough to be noticed","adj. 明显的；可感知的；可观的","adj.",3,0,"toefl",7230,1.8,""],
  ["apprehend","/ˌæprɪˈhend/","v. to arrest or understand","v. 逮捕；理解；忧虑","v.",3,0,"toefl",7230,1.8,"0:apprehends/1:apprehending/2:apprehended"],
  ["appropriate","/əˈproʊpriət/","v. to take for one's own use","v. 挪用；占用；adj. 适当的","v.",4,0,"toefl",6123,2.4,"0:appropriates/1:appropriating/2:appropriated"],
  ["apt","/æpt/","adj. appropriate or having a tendency","adj. 恰当的；有……倾向的","adj.",3,0,"toefl",6789,2.1,""],
  ["arbitrary","/ˈɑːrbɪtreri/","adj. based on random choice","adj. 任意的；武断的；专制的","adj.",3,0,"toefl",4987,2.8,""],
  ["ardent","/ˈɑːrdnt/","adj. enthusiastic or passionate","adj. 热情的；热心的；炽热的","adj.",3,0,"toefl",6789,2.1,""],
  ["arid","/ˈærɪd/","adj. having little or no rain","adj. 干旱的；干燥的；枯燥的","adj.",3,0,"toefl",7230,1.8,""],
  ["articulate","/ɑːrˈtɪkjuleɪt/","v. to express clearly and effectively","v. 明确表达；adj. 善于表达的","v.",3,0,"toefl",6123,2.4,"0:articulates/1:articulating/2:articulated"],
  ["ascertain","/ˌæsərˈteɪn/","v. to find out for certain","v. 查明；确定；弄清","v.",3,0,"toefl",7230,1.8,"0:ascertains/1:ascertaining/2:ascertained"],
  ["aspire","/əˈspaɪər/","v. to direct one's hopes toward","v. 渴望；有志于；追求","v.",3,0,"toefl",7230,1.8,"0:aspires/1:aspiring/2:aspired"],
  ["assault","/əˈsɔːlt/","n. a violent physical attack","n. 攻击；袭击；v. 攻击","n.",3,0,"toefl",5432,2.6,"0:assaults/1:assaulting/2:assaulted"],
  ["assert","/əˈsɜːrt/","v. to state a fact or belief confidently","v. 断言；主张；坚持；维护","v.",3,0,"toefl",4890,2.9,"0:asserts/1:asserting/2:asserted"],
  ["assimilate","/əˈsɪməleɪt/","v. to absorb and integrate fully","v. 吸收；同化；融入","v.",3,0,"toefl",7890,1.6,"0:assimilates/1:assimilating/2:assimilated"],
  ["attain","/əˈteɪn/","v. to succeed in achieving","v. 达到；获得；实现","v.",3,0,"toefl",4567,2.9,"0:attains/1:attaining/2:attained"],
  ["attribute","/əˈtrɪbjuːt/","v. to regard as being caused by","v. 归因于；n. 属性；特征","v.",4,0,"toefl",3876,3.3,"0:attributes/1:attributing/2:attributed"],
  ["audit","/ˈɔːdɪt/","n. an official inspection of accounts","n. 审计；审查；v. 审计","n.",3,0,"toefl",6789,2.1,"0:audits/1:auditing/2:audited"],
  ["augment","/ɔːɡˈment/","v. to make greater by adding to","v. 增加；增大；增强","v.",3,0,"toefl",7230,1.8,"0:augments/1:augmenting/2:augmented"],
  ["austere","/ɔːˈstɪr/","adj. severe in manner or appearance","adj. 严厉的；朴素的；简朴的","adj.",3,0,"toefl",7230,1.8,""],
  ["authentic","/ɔːˈθentɪk/","adj. of undisputed origin; genuine","adj. 真正的；真实的；可信的","adj.",3,0,"toefl",4987,2.8,""],
  ["authorize","/ˈɔːθəraɪz/","v. to give official permission","v. 授权；批准；许可","v.",3,0,"toefl",5120,2.8,"0:authorizes/1:authorizing/2:authorized"],
  ["autonomous","/ɔːˈtɑːnəməs/","adj. having self-government","adj. 自治的；自主的","adj.",3,0,"toefl",6345,2.3,""],
  ["avail","/əˈveɪl/","v. to be of use or advantage","v. 有益于；有助于；n. 效用","v.",3,0,"toefl",8345,1.4,"0:avails/1:availing/2:availed"],
  ["avert","/əˈvɜːrt/","v. to turn away or prevent","v. 避免；防止；转移","v.",3,0,"toefl",7230,1.8,"0:averts/1:averting/2:averted"],
  ["avid","/ˈævɪd/","adj. having a keen interest","adj. 渴望的；热衷的；贪婪的","adj.",3,0,"toefl",7230,1.8,""],
  ["baffle","/ˈbæfl/","v. to totally bewilder","v. 使困惑；难住；阻碍","v.",3,0,"toefl",6123,2.4,"0:baffles/1:baffling/2:baffled"],
  ["barren","/ˈbærən/","adj. unable to produce vegetation","adj. 贫瘠的；不育的；无效果的","adj.",3,0,"toefl",6789,2.1,""],
  ["beckon","/ˈbekən/","v. to make a gesture to encourage","v. 招手；召唤；吸引","v.",3,0,"toefl",7230,1.8,"0:beckons/1:beckoning/2:beckoned"],
  ["belligerent","/bəˈlɪdʒərənt/","adj. hostile and aggressive","adj. 好战的；交战的；敌对的","adj.",3,0,"toefl",8345,1.4,""],
  ["benevolent","/bəˈnevələnt/","adj. well-meaning and kindly","adj. 仁慈的；慈善的","adj.",3,0,"toefl",8345,1.4,""],
  ["besiege","/bɪˈsiːdʒ/","v. to surround with armed forces","v. 包围；围困；使烦恼","v.",3,0,"toefl",7890,1.6,"0:besieges/1:besieging/2:besieged"],
  ["bestow","/bɪˈstoʊ/","v. to confer or present an honor","v. 授予；给予；赠予","v.",3,0,"toefl",6789,2.1,"0:bestows/1:bestowing/2:bestowed"],
  ["bewilder","/bɪˈwɪldər/","v. to cause to become perplexed","v. 使迷惑；使糊涂","v.",3,0,"toefl",6789,2.1,"0:bewilders/1:bewildering/2:bewildered"],
  ["bias","/ˈbaɪəs/","n. inclination or prejudice","n. 偏见；偏爱；v. 使有偏见","n.",3,0,"toefl",5678,2.5,"0:biases/1:biasing/2:biased"],
  ["bizarre","/bɪˈzɑːr/","adj. very strange or unusual","adj. 奇异的；古怪的","adj.",3,0,"toefl",6123,2.4,""],
  ["bland","/blænd/","adj. lacking strong features","adj. 温和的；平淡的；乏味的","adj.",3,0,"toefl",7230,1.8,""],
  ["blaze","/bleɪz/","v. to burn fiercely or brightly","v. 燃烧；闪耀；开拓；n. 火焰","v.",3,0,"toefl",6789,2.1,"0:blazes/1:blazing/2:blazed"],
  ["bleak","/bliːk/","adj. cold and miserable; not hopeful","adj. 阴冷的；荒凉的；黯淡的","adj.",3,0,"toefl",6123,2.4,""],
  ["blemish","/ˈblemɪʃ/","n. a small mark that spoils","n. 瑕疵；污点；v. 玷污","n.",3,0,"toefl",7890,1.6,"0:blemishes/1:blemishing/2:blemished"],
  ["blunder","/ˈblʌndər/","n. a stupid or careless mistake","n. 错误；大错；v. 犯大错","n.",3,0,"toefl",6789,2.1,"0:blunders/1:blundering/2:blundered"],
  ["blunt","/blʌnt/","adj. having a worn-down edge","adj. 钝的；直率的；v. 使变钝","adj.",3,0,"toefl",6123,2.4,""],
  ["boycott","/ˈbɔɪkɑːt/","v. to refuse to buy or participate","v. 抵制；排斥；n. 抵制","v.",3,0,"toefl",6123,2.4,"0:boycotts/1:boycotting/2:boycotted"],
  ["breach","/briːtʃ/","n. an act of breaking a law","n. 违反；破坏；缺口；v. 违反","n.",3,0,"toefl",5678,2.5,"0:breaches/1:breaching/2:breached"],
  ["brisk","/brɪsk/","adj. active, fast, and energetic","adj. 轻快的；活泼的；兴隆的","adj.",3,0,"toefl",6789,2.1,""],
  ["brittle","/ˈbrɪtl/","adj. hard but easily broken","adj. 易碎的；脆弱的；易怒的","adj.",3,0,"toefl",7230,1.8,""],
  ["brutal","/ˈbruːtl/","adj. savagely violent","adj. 野蛮的；残忍的；无情的","adj.",3,0,"toefl",5678,2.5,""],
];

const IELTS = [
  ["accommodation","/əˌkɑːməˈdeɪʃn/","n. a room or building to live in","n. 住宿；住处；适应","n.",4,0,"ielts",3876,3.3,"0:accommodations"],
  ["accountant","/əˈkaʊntənt/","n. a person who manages finances","n. 会计师；会计","n.",3,0,"ielts",5678,2.5,"0:accountants"],
  ["accredit","/əˈkredɪt/","v. to officially recognize","v. 认可；授权；把……归于","v.",3,0,"ielts",8345,1.4,"0:accredits/1:accrediting/2:accredited"],
  ["adhere","/ədˈhɪr/","v. to stick firmly to","v. 遵守；粘附；坚持","v.",3,0,"ielts",5678,2.5,"0:adheres/1:adhering/2:adhered"],
  ["adjourn","/əˈdʒɜːrn/","v. to break off a meeting","v. 休会；休庭；延期","v.",3,0,"ielts",8345,1.4,"0:adjourns/1:adjourning/2:adjourned"],
  ["adolescent","/ˌædəˈlesnt/","n. a young person developing into an adult","n. 青少年；adj. 青春期的","n.",3,0,"ielts",5120,2.8,"0:adolescents"],
  ["adverse","/ˈædvɜːrs/","adj. harmful or unfavorable","adj. 不利的；相反的；敌对的","adj.",3,0,"ielts",5678,2.5,""],
  ["aesthetic","/esˈθetɪk/","adj. concerned with beauty","adj. 美学的；审美的；美观的","adj.",3,0,"ielts",6789,2.1,""],
  ["aggregate","/ˈæɡrɪɡət/","n. a whole formed by combining elements","n. 合计；集合体；v. 聚集","n.",3,0,"ielts",7234,1.8,"0:aggregates/1:aggregating/2:aggregated"],
  ["allay","/əˈleɪ/","v. to diminish or put at rest","v. 减轻；消除；平息","v.",3,0,"ielts",8345,1.4,"0:allays/1:allaying/2:allayed"],
  ["allege","/əˈledʒ/","v. to claim or assert without proof","v. 指控；宣称；断言","v.",3,0,"ielts",5432,2.6,"0:alleges/1:alleging/2:alleged"],
  ["alleviate","/əˈliːvieɪt/","v. to make suffering less severe","v. 减轻；缓和；缓解","v.",3,0,"ielts",6780,2.1,"0:alleviates/1:alleviating/2:alleviated"],
  ["allocate","/ˈæləkeɪt/","v. to distribute for a purpose","v. 分配；拨出；指定","v.",3,0,"ielts",5432,2.6,"0:allocates/1:allocating/2:allocated"],
  ["allure","/əˈlʊr/","v. to powerfully attract or charm","v. 诱惑；吸引；n. 魅力","v.",3,0,"ielts",7890,1.6,"0:allures/1:alluring/2:allured"],
  ["ambiguous","/æmˈbɪɡjuəs/","adj. open to more than one interpretation","adj. 模棱两可的；含糊的","adj.",3,0,"ielts",5890,2.4,""],
  ["ameliorate","/əˈmiːliəreɪt/","v. to make something bad better","v. 改善；改良；改进","v.",3,0,"ielts",8345,1.4,"0:ameliorates/1:ameliorating/2:ameliorated"],
  ["amenity","/əˈmenəti/","n. a desirable feature of a place","n. 便利设施；舒适；礼仪","n.",3,0,"ielts",7230,1.8,"0:amenities"],
  ["analogy","/əˈnælədʒi/","n. a comparison between things","n. 类比；比喻；类推","n.",3,0,"ielts",6345,2.3,"0:analogies"],
  ["annex","/əˈneks/","v. to add as an extra part","v. 附加；吞并；n. 附属建筑","v.",3,0,"ielts",6789,2.1,"0:annexes/1:annexing/2:annexed"],
  ["anonymous","/əˈnɑːnɪməs/","adj. having no known name","adj. 匿名的；无名的","adj.",3,0,"ielts",5678,2.5,""],
  ["appraisal","/əˈpreɪzl/","n. an assessment of worth","n. 评价；评估；鉴定","n.",3,0,"ielts",7230,1.8,"0:appraisals"],
  ["appreciable","/əˈpriːʃəbl/","adj. large enough to be noticed","adj. 明显的；可观的","adj.",3,0,"ielts",7230,1.8,""],
  ["apprentice","/əˈprentɪs/","n. a person learning a trade","n. 学徒；v. 使当学徒","n.",3,0,"ielts",7230,1.8,"0:apprentices/1:apprenticing/2:apprenticed"],
  ["arbitrate","/ˈɑːrbɪtreɪt/","v. to settle a dispute officially","v. 仲裁；公断；裁决","v.",3,0,"ielts",8345,1.4,"0:arbitrates/1:arbitrating/2:arbitrated"],
  ["articulate","/ɑːrˈtɪkjuleɪt/","v. to express clearly","v. 明确表达；adj. 善于表达的","v.",3,0,"ielts",6123,2.4,"0:articulates/1:articulating/2:articulated"],
  ["ascertain","/ˌæsərˈteɪn/","v. to find out for certain","v. 查明；确定；弄清","v.",3,0,"ielts",7230,1.8,"0:ascertains/1:ascertaining/2:ascertained"],
  ["aspire","/əˈspaɪər/","v. to direct one's hopes toward","v. 渴望；有志于；追求","v.",3,0,"ielts",7230,1.8,"0:aspires/1:aspiring/2:aspired"],
  ["assault","/əˈsɔːlt/","n. a violent physical attack","n. 攻击；袭击；v. 攻击","n.",3,0,"ielts",5432,2.6,"0:assaults/1:assaulting/2:assaulted"],
  ["assent","/əˈsent/","n. the expression of approval","n. 同意；赞成；v. 同意","n.",3,0,"ielts",7890,1.6,"0:assents/1:assenting/2:assented"],
  ["assert","/əˈsɜːrt/","v. to state a fact confidently","v. 断言；主张；维护","v.",3,0,"ielts",4890,2.9,"0:asserts/1:asserting/2:asserted"],
  ["assimilate","/əˈsɪməleɪt/","v. to absorb and integrate","v. 吸收；同化；融入","v.",3,0,"ielts",7890,1.6,"0:assimilates/1:assimilating/2:assimilated"],
  ["asylum","/əˈsaɪləm/","n. protection granted by a state","n. 庇护；避难所；精神病院","n.",3,0,"ielts",7230,1.8,"0:asylums"],
  ["atrocity","/əˈtrɑːsəti/","n. an extremely wicked act","n. 暴行；残忍；残暴","n.",3,0,"ielts",8345,1.4,"0:atrocities"],
  ["attrition","/əˈtrɪʃn/","n. gradual reduction in numbers","n. 消耗；磨损；人员流失","n.",3,0,"ielts",7890,1.6,""],
  ["auction","/ˈɔːkʃn/","n. a public sale of goods","n. 拍卖；v. 拍卖","n.",3,0,"ielts",6123,2.4,"0:auctions/1:auctioning/2:auctioned"],
  ["audit","/ˈɔːdɪt/","n. an official inspection of accounts","n. 审计；审查；v. 审计","n.",3,0,"ielts",6789,2.1,"0:audits/1:auditing/2:audited"],
  ["augment","/ɔːɡˈment/","v. to make greater by adding to","v. 增加；增大；增强","v.",3,0,"ielts",7230,1.8,"0:augments/1:augmenting/2:augmented"],
  ["austerity","/ɔːˈsterəti/","n. sternness or severity","n. 严厉；朴素；紧缩","n.",3,0,"ielts",7890,1.6,""],
  ["authenticate","/ɔːˈθentɪkeɪt/","v. to prove or show to be genuine","v. 证明……为真；验证","v.",3,0,"ielts",7230,1.8,"0:authenticates/1:authenticating/2:authenticated"],
  ["autonomous","/ɔːˈtɑːnəməs/","adj. having self-government","adj. 自治的；自主的","adj.",3,0,"ielts",6345,2.3,""],
  ["avalanche","/ˈævəlæntʃ/","n. a mass of snow falling rapidly","n. 雪崩；大量；v. 雪崩","n.",3,0,"ielts",8345,1.4,"0:avalanches"],
  ["avert","/əˈvɜːrt/","v. to turn away or prevent","v. 避免；防止；转移","v.",3,0,"ielts",7230,1.8,"0:averts/1:averting/2:averted"],
  ["bachelor","/ˈbætʃələr/","n. a man who has never married","n. 单身汉；学士","n.",3,0,"ielts",5678,2.5,"0:bachelors"],
  ["baffle","/ˈbæfl/","v. to totally bewilder","v. 使困惑；难住；阻碍","v.",3,0,"ielts",6123,2.4,"0:baffles/1:baffling/2:baffled"],
  ["ballot","/ˈbælət/","n. a process of secret voting","n. 投票；选票；v. 投票表决","n.",3,0,"ielts",6789,2.1,"0:ballots/1:balloting/2:balloted"],
  ["bankruptcy","/ˈbæŋkrʌptsi/","n. the state of being bankrupt","n. 破产；倒闭","n.",3,0,"ielts",6123,2.4,"0:bankruptcies"],
  ["barrister","/ˈbærɪstər/","n. a lawyer entitled to practice","n. 律师；大律师","n.",3,0,"ielts",7230,1.8,"0:barristers"],
  ["beckon","/ˈbekən/","v. to make a gesture to encourage","v. 招手；召唤；吸引","v.",3,0,"ielts",7230,1.8,"0:beckons/1:beckoning/2:beckoned"],
  ["beneficiary","/ˌbenɪˈfɪʃieri/","n. a person who derives advantage","n. 受益人；受惠者","n.",3,0,"ielts",6789,2.1,"0:beneficiaries"],
  ["benevolent","/bəˈnevələnt/","adj. well-meaning and kindly","adj. 仁慈的；慈善的","adj.",3,0,"ielts",8345,1.4,""],
  ["besiege","/bɪˈsiːdʒ/","v. to surround with armed forces","v. 包围；围困；使烦恼","v.",3,0,"ielts",7890,1.6,"0:besieges/1:besieging/2:besieged"],
  ["beverage","/ˈbevərɪdʒ/","n. a drink other than water","n. 饮料","n.",3,0,"ielts",6123,2.4,"0:beverages"],
  ["bibliography","/ˌbɪbliˈɑːɡrəfi/","n. a list of books referred to","n. 参考书目；文献目录","n.",3,0,"ielts",7230,1.8,"0:bibliographies"],
  ["bilateral","/ˌbaɪˈlætərəl/","adj. involving two parties","adj. 双边的；两侧的","adj.",3,0,"ielts",6123,2.4,""],
  ["bizarre","/bɪˈzɑːr/","adj. very strange or unusual","adj. 奇异的；古怪的","adj.",3,0,"ielts",6123,2.4,""],
  ["blaze","/bleɪz/","n. a very large or fiercely burning fire","n. 火焰；光辉；v. 燃烧","n.",3,0,"ielts",6789,2.1,"0:blazes/1:blazing/2:blazed"],
  ["blemish","/ˈblemɪʃ/","n. a small mark that spoils","n. 瑕疵；污点；v. 玷污","n.",3,0,"ielts",7890,1.6,"0:blemishes/1:blemishing/2:blemished"],
  ["blueprint","/ˈbluːprɪnt/","n. a design plan or drawing","n. 蓝图；行动计划；方案","n.",3,0,"ielts",7230,1.8,"0:blueprints"],
  ["boycott","/ˈbɔɪkɑːt/","v. to refuse to buy or participate","v. 抵制；排斥；n. 抵制","v.",3,0,"ielts",6123,2.4,"0:boycotts/1:boycotting/2:boycotted"],
  ["breach","/briːtʃ/","n. an act of breaking a law","n. 违反；破坏；缺口；v. 违反","n.",3,0,"ielts",5678,2.5,"0:breaches/1:breaching/2:breached"],
  ["bribery","/ˈbraɪbəri/","n. the act of giving a bribe","n. 贿赂；行贿","n.",3,0,"ielts",7230,1.8,""],
  ["brisk","/brɪsk/","adj. active, fast, and energetic","adj. 轻快的；活泼的；兴隆的","adj.",3,0,"ielts",6789,2.1,""],
  ["brochure","/broʊˈʃʊr/","n. a small book containing information","n. 小册子；手册","n.",3,0,"ielts",6123,2.4,"0:brochures"],
  ["budgetary","/ˈbʌdʒɪteri/","adj. relating to a budget","adj. 预算的","adj.",3,0,"ielts",6789,2.1,""],
  ["bureaucracy","/bjʊˈrɑːkrəsi/","n. a system of government with many rules","n. 官僚机构；官僚主义","n.",3,0,"ielts",7890,1.6,"0:bureaucracies"],
  ["calamity","/kəˈlæməti/","n. an event causing great damage","n. 灾难；不幸事件","n.",3,0,"ielts",7890,1.6,"0:calamities"],
  ["camouflage","/ˈkæməflɑːʒ/","n. disguise to blend with surroundings","n. 伪装；掩饰；v. 伪装","n.",3,0,"ielts",8345,1.4,""],
  ["candid","/ˈkændɪd/","adj. truthful and straightforward","adj. 坦率的；直言的；公正的","adj.",3,0,"ielts",7230,1.8,""],
  ["cannabis","/ˈkænəbɪs/","n. a plant used as a drug","n. 大麻","n.",2,0,"ielts",8345,1.4,""],
  ["canvas","/ˈkænvəs/","n. a strong unbleached cloth","n. 帆布；画布；油画","n.",3,0,"ielts",7230,1.8,"0:canvases"],
  ["capability","/ˌkeɪpəˈbɪləti/","n. the power or ability to do something","n. 能力；才能；容量","n.",3,0,"ielts",4987,2.8,"0:capabilities"],
  ["caption","/ˈkæpʃn/","n. a title or brief explanation","n. 标题；字幕；说明文字","n.",3,0,"ielts",7230,1.8,"0:captions"],
  ["cardinal","/ˈkɑːrdɪnl/","adj. of the greatest importance","adj. 最重要的；基本的；n. 红衣主教","adj.",3,0,"ielts",8345,1.4,""],
  ["carnival","/ˈkɑːrnɪvl/","n. a festival or celebration","n. 狂欢节；嘉年华","n.",3,0,"ielts",7230,1.8,"0:carnivals"],
  ["catalogue","/ˈkætəlɔːɡ/","n. a complete list of items","n. 目录；v. 编目录","n.",3,0,"ielts",5678,2.5,"0:catalogues/1:cataloguing/2:catalogued"],
  ["catastrophe","/kəˈtæstrəfi/","n. an event causing great damage","n. 灾难；大祸；彻底失败","n.",3,0,"ielts",6123,2.4,"0:catastrophes"],
  ["cater","/ˈkeɪtər/","v. to provide what is wanted","v. 满足需求；提供饮食；迎合","v.",3,0,"ielts",5678,2.5,"0:caters/1:catering/2:catered"],
  ["caution","/ˈkɔːʃn/","n. care taken to avoid danger","n. 谨慎；小心；警告；v. 警告","n.",3,0,"ielts",4987,2.8,""],
  ["cavity","/ˈkævəti/","n. an empty space within a solid","n. 洞；腔；蛀牙","n.",3,0,"ielts",7230,1.8,"0:cavities"],
  ["census","/ˈsensəs/","n. an official count of a population","n. 人口普查；统计","n.",3,0,"ielts",6123,2.4,"0:censuses"],
  ["certify","/ˈsɜːrtɪfaɪ/","v. to formally confirm or attest","v. 证明；认证；保证","v.",3,0,"ielts",5432,2.6,"0:certifies/1:certifying/2:certified"],
  ["chronic","/ˈkrɑːnɪk/","adj. persisting for a long time","adj. 慢性的；长期的","adj.",3,0,"ielts",6123,2.4,""],
  ["circulation","/ˌsɜːrkjəˈleɪʃn/","n. movement around a closed system","n. 循环；流通；发行量","n.",3,0,"ielts",4987,2.8,""],
  ["clarity","/ˈklærəti/","n. the quality of being clear","n. 清晰；清楚；明晰","n.",3,0,"ielts",5432,2.6,""],
];

const GRE = [
  ["aberration","/ˌæbəˈreɪʃn/","n. a departure from what is normal","n. 反常；偏差；越轨","n.",4,0,"gre",8345,1.4,"0:aberrations"],
  ["abeyance","/əˈbeɪəns/","n. a state of temporary disuse","n. 中止；暂停；搁置","n.",5,0,"gre",8900,1.2,""],
  ["abjure","/əbˈdʒʊr/","v. to solemnly renounce a belief","v. 发誓放弃；公开放弃","v.",5,0,"gre",8345,1.4,"0:abjures/1:abjuring/2:abjured"],
  ["abnegate","/ˈæbnɪɡeɪt/","v. to renounce or reject","v. 放弃；拒绝；克制","v.",5,0,"gre",8900,1.2,"0:abnegates/1:abnegating/2:abnegated"],
  ["abrogate","/ˈæbrəɡeɪt/","v. to repeal or do away with","v. 废除；取消","v.",4,0,"gre",8345,1.4,"0:abrogates/1:abrogating/2:abrogated"],
  ["abscission","/æbˈsɪʒn/","n. the natural detachment of parts","n. 切断；脱落；切除","n.",5,0,"gre",8900,1.2,""],
  ["abscond","/əbˈskɑːnd/","v. to leave hurriedly and secretly","v. 潜逃；逃亡；失踪","v.",4,0,"gre",8345,1.4,"0:absconds/1:absconding/2:absconded"],
  ["abstemious","/əbˈstiːmiəs/","adj. not self-indulgent","adj. 有节制的；饮食适度的","adj.",5,0,"gre",8345,1.4,""],
  ["abstruse","/əbˈstruːs/","adj. difficult to understand","adj. 深奥的；难懂的","adj.",4,0,"gre",8345,1.4,""],
  ["accolade","/ˈækəleɪd/","n. an award or privilege granted","n. 荣誉；赞扬；奖赏","n.",4,0,"gre",8345,1.4,"0:accolades"],
  ["acerbic","/əˈsɜːrbɪk/","adj. sharp and forthright","adj. 尖刻的；辛辣的；酸的","adj.",4,0,"gre",8345,1.4,""],
  ["acquiesce","/ˌækwiˈes/","v. to accept something reluctantly","v. 默许；勉强同意","v.",4,0,"gre",8345,1.4,"0:acquiesces/1:acquiescing/2:acquiesced"],
  ["acrimony","/ˈækrɪmoʊni/","n. bitterness or ill feeling","n. 尖刻；刻薄；激烈","n.",4,0,"gre",8345,1.4,""],
  ["admonish","/ədˈmɑːnɪʃ/","v. to warn or reprimand firmly","v. 告诫；警告；责备","v.",4,0,"gre",8345,1.4,"0:admonishes/1:admonishing/2:admonished"],
  ["adroit","/əˈdrɔɪt/","adj. clever or skillful","adj. 机敏的；灵巧的；熟练的","adj.",4,0,"gre",8345,1.4,""],
  ["adulation","/ˌædʒəˈleɪʃn/","n. excessive admiration or praise","n. 奉承；谄媚；过度称赞","n.",4,0,"gre",8345,1.4,""],
  ["adulterate","/əˈdʌltəreɪt/","v. to make impure by adding inferior","v. 掺假；掺杂","v.",4,0,"gre",8345,1.4,"0:adulterates/1:adulterating/2:adulterated"],
  ["aesthetic","/esˈθetɪk/","adj. concerned with beauty or art","adj. 美学的；审美的；美观的","adj.",3,0,"gre",6789,2.1,""],
  ["aggregate","/ˈæɡrɪɡət/","v. to collect into a whole","v. 聚集；合计；n. 总数","v.",3,0,"gre",7234,1.8,"0:aggregates/1:aggregating/2:aggregated"],
  ["alacrity","/əˈlækrəti/","n. brisk and cheerful readiness","n. 爽快；敏捷；乐意","n.",4,0,"gre",8345,1.4,""],
  ["alchemy","/ˈælkəmi/","n. medieval forerunner of chemistry","n. 炼金术；魔力；奇妙的变化","n.",4,0,"gre",8345,1.4,""],
  ["allay","/əˈleɪ/","v. to diminish or put at rest","v. 减轻；消除；平息","v.",4,0,"gre",8345,1.4,"0:allays/1:allaying/2:allayed"],
  ["alleviate","/əˈliːvieɪt/","v. to make suffering less severe","v. 减轻；缓和；缓解","v.",3,0,"gre",6780,2.1,"0:alleviates/1:alleviating/2:alleviated"],
  ["alloy","/ˈælɔɪ/","n. a metal made by combining two elements","n. 合金；v. 使成合金；贬低","n.",4,0,"gre",8345,1.4,"0:alloys"],
  ["allure","/əˈlʊr/","v. to powerfully attract or charm","v. 诱惑；吸引；n. 魅力","v.",4,0,"gre",7890,1.6,"0:allures/1:alluring/2:allured"],
  ["amalgamate","/əˈmælɡəmeɪt/","v. to combine or unite","v. 合并；联合；混合","v.",4,0,"gre",8345,1.4,"0:amalgamates/1:amalgamating/2:amalgamated"],
  ["ambiguous","/æmˈbɪɡjuəs/","adj. open to interpretation","adj. 模棱两可的；含糊的","adj.",3,0,"gre",5890,2.4,""],
  ["ambivalent","/æmˈbɪvələnt/","adj. having mixed feelings","adj. 矛盾的；犹豫不决的","adj.",4,0,"gre",7230,1.8,""],
  ["ameliorate","/əˈmiːliəreɪt/","v. to make something bad better","v. 改善；改良；改进","v.",4,0,"gre",8345,1.4,"0:ameliorates/1:ameliorating/2:ameliorated"],
  ["amenable","/əˈmiːnəbl/","adj. open and responsive to suggestion","adj. 顺从的；服从的；有义务的","adj.",4,0,"gre",8345,1.4,""],
  ["amulet","/ˈæmjʊlət/","n. an ornament worn as protection","n. 护身符；驱邪物","n.",5,0,"gre",8900,1.2,"0:amulets"],
  ["anachronism","/əˈnækrənɪzəm/","n. a thing belonging to a wrong time","n. 时代错误；不合时宜","n.",4,0,"gre",8345,1.4,"0:anachronisms"],
  ["analgesic","/ˌænəlˈdʒiːzɪk/","n. a pain-relieving drug","n. 止痛药；adj. 止痛的","n.",4,0,"gre",8345,1.4,"0:analgesics"],
  ["anathema","/əˈnæθəmə/","n. something that one vehemently dislikes","n. 诅咒；令人厌恶的事物","n.",5,0,"gre",8900,1.2,""],
  ["anecdote","/ˈænɪkdoʊt/","n. a short amusing real story","n. 轶事；趣闻；短故事","n.",3,0,"gre",6123,2.4,"0:anecdotes"],
  ["animosity","/ˌænɪˈmɑːsəti/","n. strong hostility","n. 敌意；仇恨；憎恶","n.",4,0,"gre",8345,1.4,""],
  ["anomaly","/əˈnɑːməli/","n. something deviating from the norm","n. 异常；反常；不规则","n.",4,0,"gre",7230,1.8,"0:anomalies"],
  ["antediluvian","/ˌæntidɪˈluːviən/","adj. of or belonging to ancient times","adj. 远古的；过时的；陈旧的","adj.",5,0,"gre",8900,1.2,""],
  ["antipathy","/ænˈtɪpəθi/","n. a deep-seated feeling of dislike","n. 反感；厌恶；憎恨","n.",4,0,"gre",8345,1.4,"0:antipathies"],
  ["apathy","/ˈæpəθi/","n. lack of interest or concern","n. 冷漠；无兴趣；无动于衷","n.",4,0,"gre",7230,1.8,""],
  ["aphorism","/ˈæfərɪzəm/","n. a pithy observation of a truth","n. 格言；警句；箴言","n.",4,0,"gre",8345,1.4,"0:aphorisms"],
  ["aplomb","/əˈplɑːm/","n. self-confidence in a difficult situation","n. 沉着；镇静；自信","n.",5,0,"gre",8900,1.2,""],
  ["apocryphal","/əˈpɑːkrɪfl/","adj. of doubtful authenticity","adj. 真实性可疑的；杜撰的","adj.",5,0,"gre",8900,1.2,""],
  ["appease","/əˈpiːz/","v. to pacify or placate","v. 安抚；平息；满足","v.",4,0,"gre",8345,1.4,"0:appeases/1:appeasing/2:appeased"],
  ["approbation","/ˌæprəˈbeɪʃn/","n. approval or praise","n. 认可；赞许；批准","n.",4,0,"gre",8345,1.4,""],
  ["arbitrary","/ˈɑːrbɪtreri/","adj. based on random choice","adj. 任意的；武断的；专制的","adj.",3,0,"gre",4987,2.8,""],
  ["arcane","/ɑːrˈkeɪn/","adj. understood by few; mysterious","adj. 神秘的；晦涩难懂的","adj.",4,0,"gre",8345,1.4,""],
  ["arduous","/ˈɑːrdʒuəs/","adj. involving great effort","adj. 艰巨的；费力的；陡峭的","adj.",4,0,"gre",7230,1.8,""],
  ["ascetic","/əˈsetɪk/","adj. characterized by severe self-discipline","adj. 苦行的；禁欲的；n. 苦行者","adj.",4,0,"gre",8345,1.4,""],
  ["asperity","/əˈsperəti/","n. harshness of tone or manner","n. 严厉；粗暴；刺耳","n.",5,0,"gre",8900,1.2,""],
  ["aspersion","/əˈspɜːrʒn/","n. an attack on someone's character","n. 诽谤；中伤；诬蔑","n.",5,0,"gre",8900,1.2,"0:aspersions"],
  ["assiduous","/əˈsɪdʒuəs/","adj. showing great care and perseverance","adj. 勤勉的；刻苦的；一丝不苟的","adj.",5,0,"gre",8900,1.2,""],
  ["attenuate","/əˈtenjueɪt/","v. to reduce the force or value of","v. 使减弱；稀释；使变细","v.",4,0,"gre",8345,1.4,"0:attenuates/1:attenuating/2:attenuated"],
  ["audacious","/ɔːˈdeɪʃəs/","adj. showing willingness to take bold risks","adj. 大胆的；无畏的；鲁莽的","adj.",4,0,"gre",8345,1.4,""],
  ["auspicious","/ɔːˈspɪʃəs/","adj. conducive to success; favorable","adj. 吉利的；有前途的；顺利的","adj.",4,0,"gre",8345,1.4,""],
  ["avarice","/ˈævərɪs/","n. extreme greed for wealth","n. 贪婪；贪财","n.",4,0,"gre",8345,1.4,""],
  ["aver","/əˈvɜːr/","v. to state or assert to be the case","v. 断言；主张；声称","v.",5,0,"gre",8900,1.2,"0:avers/1:averring/2:averred"],
  ["axiom","/ˈæksiəm/","n. a statement taken to be true","n. 公理；原理；格言","n.",4,0,"gre",8345,1.4,"0:axioms"],
  ["baleful","/ˈbeɪlfl/","adj. threatening harm; menacing","adj. 有害的；恶意的；威胁的","adj.",5,0,"gre",8900,1.2,""],
  ["banal","/bəˈnæl/","adj. so lacking in originality","adj. 陈腐的；平庸的；老一套的","adj.",4,0,"gre",8345,1.4,""],
  ["bastion","/ˈbæstʃən/","n. an institution defending something","n. 堡垒；捍卫者；支柱","n.",4,0,"gre",8345,1.4,"0:bastions"],
  ["bellicose","/ˈbelɪkoʊs/","adj. demonstrating aggression","adj. 好战的；好斗的","adj.",5,0,"gre",8900,1.2,""],
  ["belligerent","/bəˈlɪdʒərənt/","adj. hostile and aggressive","adj. 好战的；交战的；敌对的","adj.",4,0,"gre",8345,1.4,""],
  ["beneficent","/bɪˈnefɪsnt/","adj. generous or doing good","adj. 仁慈的；慈善的；行善的","adj.",4,0,"gre",8345,1.4,""],
  ["benevolent","/bəˈnevələnt/","adj. well-meaning and kindly","adj. 仁慈的；慈善的","adj.",3,0,"gre",8345,1.4,""],
  ["bequeath","/bɪˈkwiːð/","v. to leave property by a will","v. 遗赠；传给","v.",4,0,"gre",8345,1.4,"0:bequeaths/1:bequeathing/2:bequeathed"],
  ["berate","/bɪˈreɪt/","v. to scold or criticize angrily","v. 严厉责备；痛骂","v.",4,0,"gre",8345,1.4,"0:berates/1:berating/2:berated"],
  ["besmirch","/bɪˈsmɜːrtʃ/","v. to damage the reputation of","v. 玷污；糟蹋；诽谤","v.",5,0,"gre",8900,1.2,"0:besmirches/1:besmirching/2:besmirched"],
  ["bilk","/bɪlk/","v. to obtain money fraudulently","v. 欺骗；诈骗；赖账","v.",5,0,"gre",8900,1.2,"0:bilks/1:bilking/2:bilked"],
  ["blandishment","/ˈblændɪʃmənt/","n. a flattering statement or action","n. 甜言蜜语；奉承","n.",5,0,"gre",8900,1.2,"0:blandishments"],
  ["blithe","/blaɪð/","adj. showing casual cheerful indifference","adj. 快乐的；无忧无虑的；轻率的","adj.",5,0,"gre",8900,1.2,""],
  ["bolster","/ˈboʊlstər/","v. to support or strengthen","v. 支持；加强；n. 垫子","v.",4,0,"gre",7230,1.8,"0:bolsters/1:bolstering/2:bolstered"],
  ["bombastic","/bɑːmˈbæstɪk/","adj. high-sounding with little meaning","adj. 夸夸其谈的；华而不实的","adj.",4,0,"gre",8345,1.4,""],
  ["boorish","/ˈbʊrɪʃ/","adj. rough and bad-mannered","adj. 粗野的；粗鲁的；笨拙的","adj.",5,0,"gre",8900,1.2,""],
  ["bourgeois","/bʊrˈʒwɑː/","adj. of or characteristic of middle class","adj. 中产阶级的；资产阶级的","adj.",4,0,"gre",8345,1.4,""],
  ["brazen","/ˈbreɪzn/","adj. bold and without shame","adj. 厚颜无耻的；无所顾忌的","adj.",4,0,"gre",8345,1.4,""],
  ["broach","/broʊtʃ/","v. to raise a sensitive subject","v. 开始讨论；提出；钻孔","v.",4,0,"gre",8345,1.4,"0:broaches/1:broaching/2:broached"],
  ["bucolic","/bjuːˈkɑːlɪk/","adj. relating to pleasant rural life","adj. 田园的；乡村的；牧羊的","adj.",4,0,"gre",8345,1.4,""],
  ["burgeon","/ˈbɜːrdʒən/","v. to begin to grow rapidly","v. 迅速增长；发芽；发展","v.",4,0,"gre",8345,1.4,"0:burgeons/1:burgeoning/2:burgeoned"],
  ["burnish","/ˈbɜːrnɪʃ/","v. to polish by rubbing","v. 擦亮；磨光；使光亮","v.",5,0,"gre",8900,1.2,"0:burnishes/1:burnishing/2:burnished"],
  ["cabal","/kəˈbæl/","n. a secret political clique","n. 阴谋集团；秘密组织","n.",5,0,"gre",8900,1.2,"0:cabals"],
  ["cacophony","/kəˈkɑːfəni/","n. a harsh discordant mixture of sounds","n. 刺耳的声音；不和谐的音","n.",4,0,"gre",8345,1.4,"0:cacophonies"],
  ["cadge","/kædʒ/","v. to ask for or obtain something","v. 乞讨；索取；讨得","v.",5,0,"gre",8900,1.2,"0:cadges/1:cadging/2:cadged"],
  ["cajole","/kəˈdʒoʊl/","v. to persuade by flattery","v. 哄骗；引诱；用甜言蜜语欺骗","v.",4,0,"gre",8345,1.4,"0:cajoles/1:cajoling/2:cajoled"],
  ["calumniate","/kəˈlʌmnieɪt/","v. to make false statements about","v. 诽谤；中伤；诬蔑","v.",5,0,"gre",8900,1.2,"0:calumniates/1:calumniating/2:calumniated"],
  ["candor","/ˈkændər/","n. the quality of being open and honest","n. 坦率；公正；直率","n.",4,0,"gre",8345,1.4,""],
];

// ==========================================
// 生成 CSV
// ==========================================

function toCsv(row) {
  // 每个字段用双引号包裹，内部双引号转义
  return row.map(field => {
    const s = String(field);
    return `"${s.replace(/"/g, '""')}"`;
  }).join(',');
}

function main() {
  const allLevels = [
    { name: 'CET-4', words: CET4 },
    { name: 'CET-6', words: CET6 },
    { name: '考研',  words: KAOYAN },
    { name: 'TOEFL', words: TOEFL },
    { name: 'IELTS', words: IELTS },
    { name: 'GRE',   words: GRE },
  ];

  // 输出统计
  console.error('=== 生成 ecdict_sample.csv ===');
  for (const level of allLevels) {
    console.error(`  ${level.name}: ${level.words.length} 词`);
  }
  const total = allLevels.reduce((sum, l) => sum + l.words.length, 0);
  console.error(`  总计: ${total} 词`);
  console.error('');

  // 输出 CSV（无表头，UTF-8）
  for (const level of allLevels) {
    for (const row of level.words) {
      process.stdout.write(toCsv(row) + '\n');
    }
  }
}

main();
